# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-name'], 'verbose_name': '\u7528\u6237\u7559\u8a00\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u4fe1\u606f'},
        ),
    ]
