# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_flag',
            field=models.CharField(max_length=32, verbose_name='action flag'),
        ),
    ]
